version: "3.5"

services:
  db:
    image: mysql:8.0.23
    container_name: db
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: casadocodigo
      MYSQL_USER: adriano
      MYSQL_PASSWORD: adriano
